apiVersion: v1
kind: Service

metadata:
  name: samp-svc
  namespace: edu
spec:
  selector:
    app: samp
  
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  #   nodePort: 32180
  # type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samp-deploy
  namespace: default
  labels:
    app: samp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samp
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/inject: "true"
      labels:
        app: samp
    spec:
      containers:
        - name: samp
          image: shclub/samp
          ports:
          - name: http
            containerPort: 8080